# Generated by Django 6.0.3 on 2026-03-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genre_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='serie_name',
            new_name='name',
        ),
    ]
