# Generated by Django 6.0.3 on 2026-03-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_author_name_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('cs', 'Čeština'), ('en', 'Angličtina')], default='cs', max_length=2),
        ),
    ]
